name: Build wasm using CMake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Clone emscripten
      uses: GuillaumeFalourd/clone-github-repo-action@v3
      with:
        owner: 'emscripten-core'
        repository: 'emsdk'
        
    - name: Installing emsdk
      run: |
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..
    
    - name: Building hello_world using cmake
      id: cmake_build
      uses: ./.github/actions/cmake-build
      with:
        target: hello_world
        build-type: Release
        build-dir: ${{github.workspace}}/build
        configure-args: -DCMAKE_TOOLCHAIN_FILE=./emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
        
    - name: Checking build
      run: |
        ls -la
        ls -la build/

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/hello_world.js
          build/hello_world.wasm
          
